services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command: start-dev
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data/
    networks:
      - orderly-net

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - orderly-net

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - orderly-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

#  geo-service-db:
#    image: postgis/postgis:16-3.4
#    environment:
#      POSTGRES_DB: orderly-geo
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5501:5432"
#    volumes:
#      - geo_volume:/var/lib/postgresql/data
#    networks:
#      - orderly-net
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres -d orderly-geo"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#
#  geo-service-liquibase:
#    image: liquibase/liquibase:4.25
#    restart: "no"
#    depends_on:
#      geo-service-db:
#        condition: service_healthy
#    volumes:
#      - ./geo-service/src/main/resources/db/changelog:/liquibase/changelog
#    command: update
#    environment:
#      LIQUIBASE_COMMAND_URL: jdbc:postgresql://geo-service-db:5432/orderly-geo
#      LIQUIBASE_COMMAND_USERNAME: postgres
#      LIQUIBASE_COMMAND_PASSWORD: postgres
#      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/db.changelog-master.yaml
#    networks:
#      - orderly-net
#
#  geo-service:
#    build:
#      context: .
#      dockerfile: geo-service/Dockerfile
#    env_file:
#      - .env.geo-service
#    ports:
#      - "8083:8083"
#    depends_on:
#      geo-service-liquibase:
#        condition: service_completed_successfully
#      eureka-server:
#        condition: service_healthy
#      keycloak:
#        condition: service_started
#    networks:
#      - orderly-net

  user-service-db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: orderly-users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5500:5432"
    volumes:
      - users_volume:/var/lib/postgresql/data
    networks:
      - orderly-net

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env.user-service
    depends_on:
      - keycloak
      - eureka-server
      - user-service-db
      - redis
    networks:
      - orderly-net

#  order-service-db:
#    image: postgres:18
#    environment:
#      POSTGRES_DB: orderly-orders
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5502:5432"
#    volumes:
#      - orders-volume:/var/lib/postgresql/data
#    networks:
#      - orderly-net
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres -d orderly-orders"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#
#  order-service-liquibase:
#    image: liquibase/liquibase:4.25
#    restart: "no"
#    depends_on:
#      order-service-db:
#        condition: service_healthy
#    volumes:
#      - ./order-service/src/main/resources/db/changelog:/liquibase/changelog
#    command: update
#    environment:
#      LIQUIBASE_COMMAND_URL: jdbc:postgresql://order-service-db:5432/orderly-orders
#      LIQUIBASE_COMMAND_USERNAME: postgres
#      LIQUIBASE_COMMAND_PASSWORD: postgres
#      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/db.changelog-master.yaml
#    networks:
#      - orderly-net
#
#  order-service:
#    build:
#      context: .
#      dockerfile: order-service/Dockerfile
#    ports:
#      - "8084:8084"
#    env_file:
#      - .env.order-service
#    depends_on:
#      keycloak:
#        condition: service_started
#      eureka-server:
#        condition: service_started
#      order-service-db:
#        condition: service_started
#      redis:
#        condition: service_started
#      order-service-liquibase:
#        condition: service_completed_successfully
#    networks:
#      - orderly-net

  restaurant-service-db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: orderly-restaurants
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5503:5432"
    volumes:
      - restaurants_volume:/var/lib/postgresql/data
    networks:
      - orderly-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d orderly-restaurants" ]
      interval: 5s
      timeout: 5s
      retries: 10

  restaurant-service-liquibase:
    image: liquibase/liquibase:4.25
    restart: "no"
    depends_on:
      restaurant-service-db:
        condition: service_healthy
    volumes:
      - ./restaurant-service/src/main/resources/db/changelog:/liquibase/changelog
    command: update
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://restaurant-service-db:5432/orderly-restaurants
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: postgres
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/db.changelog-master.yaml
    networks:
      - orderly-net

  restaurant-service:
    build:
      context: .
      dockerfile: restaurant-service/Dockerfile
    env_file:
      - .env.restaurant-service
    ports:
      - "8085:8085"
    depends_on:
      restaurant-service-liquibase:
        condition: service_completed_successfully
      eureka-server:
        condition: service_healthy
      keycloak:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - orderly-net

volumes:
  users_volume:
  geo_volume:
  keycloak_data:
  orders-volume:
  restaurants_volume:

networks:
  orderly-net:
    driver: bridge
