services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command: start-dev
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data/
    networks:
      - orderly-net

#  redis:
#    image: redis:7.2
#    ports:
#      - "6379:6379"
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 5s
#    networks:
#      - orderly-net

  minio:
    image: quay.io/minio/minio:RELEASE.2025-07-23T15-54-02Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_volume:/data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      orderly-net:

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - orderly-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

#  geo-service-db:
#    image: postgis/postgis:16-3.4
#    environment:
#      POSTGRES_DB: orderly-geo
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5501:5432"
#    volumes:
#      - geo_volume:/var/lib/postgresql/data
#    networks:
#      - orderly-net
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres -d orderly-geo"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#
#  geo-service-liquibase:
#    image: liquibase/liquibase:4.25
#    restart: "no"
#    depends_on:
#      geo-service-db:
#        condition: service_healthy
#    volumes:
#      - ./geo-service/src/main/resources/db/changelog:/liquibase/changelog
#    command: update
#    environment:
#      LIQUIBASE_COMMAND_URL: jdbc:postgresql://geo-service-db:5432/orderly-geo
#      LIQUIBASE_COMMAND_USERNAME: postgres
#      LIQUIBASE_COMMAND_PASSWORD: postgres
#      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/db.changelog-master.yaml
#    networks:
#      - orderly-net
#
#  geo-service:
#    build:
#      context: .
#      dockerfile: geo-service/Dockerfile
#    env_file:
#      - .env.geo-service
#    ports:
#      - "8083:8083"
#    depends_on:
#      geo-service-liquibase:
#        condition: service_completed_successfully
#      eureka-server:
#        condition: service_healthy
#      keycloak:
#        condition: service_started
#    networks:
#      - orderly-net
#
#  user-service-db:
#    image: postgis/postgis:16-3.4
#    environment:
#      POSTGRES_DB: orderly-users
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5500:5432"
#    volumes:
#      - users_volume:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres -d orderly-users" ]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#    networks:
#      - orderly-net
#
#  user-service:
#    build:
#      context: .
#      dockerfile: user-service/Dockerfile
#    ports:
#      - "8082:8082"
#    env_file:
#      - .env.user-service
#    depends_on:
#      user-service-db:
#        condition: service_healthy
#      eureka-server:
#        condition: service_healthy
#      keycloak:
#        condition: service_started
#      redis:
#        condition: service_healthy
#      minio:
#        condition: service_healthy
#    networks:
#      - orderly-net

#  order-service-db:
#    image: postgis/postgis:16-3.4
#    environment:
#      POSTGRES_DB: orderly-orders
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5502:5432"
#    volumes:
#      - orders-volume:/var/lib/postgresql/data
#    networks:
#      - orderly-net
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres -d orderly-orders"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#
#  order-service-liquibase:
#    image: liquibase/liquibase:4.25
#    restart: "no"
#    depends_on:
#      order-service-db:
#        condition: service_healthy
#    volumes:
#      - ./order-service/src/main/resources/db/changelog:/liquibase/changelog
#    command: update
#    environment:
#      LIQUIBASE_COMMAND_URL: jdbc:postgresql://order-service-db:5432/orderly-orders
#      LIQUIBASE_COMMAND_USERNAME: postgres
#      LIQUIBASE_COMMAND_PASSWORD: postgres
#      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/db.changelog-master.yaml
#    networks:
#      - orderly-net
#
#  order-service:
#    build:
#      context: .
#      dockerfile: order-service/Dockerfile
#    ports:
#      - "8084:8084"
#    environment:
#      SPRING_R2DBC_URL: r2dbc:postgresql://order-service-db:5432/orderly-orders
#      SPRING_R2DBC_USERNAME: postgres
#      SPRING_R2DBC_PASSWORD: postgres
#    depends_on:
#      keycloak:
#        condition: service_started
#      eureka-server:
#        condition: service_healthy
#      order-service-db:
#        condition: service_healthy
#      order-service-liquibase:
#        condition: service_completed_successfully
#      kafka:
#        condition: service_started
#    networks:
#      - orderly-net

#  restaurant-service-db:
#    image: postgis/postgis:16-3.4
#    environment:
#      POSTGRES_DB: orderly-restaurants
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5503:5432"
#    volumes:
#      - restaurants_volume:/var/lib/postgresql/data
#    networks:
#      - orderly-net
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres -d orderly-restaurants" ]
#      interval: 5s
#      timeout: 5s
#      retries: 10

#  restaurant-service-liquibase:
#    image: liquibase/liquibase:4.25
#    restart: "no"
#    depends_on:
#      restaurant-service-db:
#        condition: service_healthy
#    volumes:
#      - ./restaurant-service/src/main/resources/db/changelog:/liquibase/changelog
#    command: update
#    environment:
#      LIQUIBASE_COMMAND_URL: jdbc:postgresql://restaurant-service-db:5432/orderly-restaurants
#      LIQUIBASE_COMMAND_USERNAME: postgres
#      LIQUIBASE_COMMAND_PASSWORD: postgres
#      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/db.changelog-master.yaml
#    networks:
#      - orderly-net

#  restaurant-service:
#    build:
#      context: .
#      dockerfile: restaurant-service/Dockerfile
#    env_file:
#      - .env.restaurant-service
#    ports:
#      - "8085:8085"
#    depends_on:
##      restaurant-service-liquibase:
##        condition: service_completed_successfully
#      eureka-server:
#        condition: service_healthy
#      keycloak:
#        condition: service_started
##      redis:
##        condition: service_healthy
#      minio:
#        condition: service_started
#      kafka:
#        condition: service_started
#    networks:
#      - orderly-net
#
  payment-service-db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: orderly-payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5504:5432"
    volumes:
      - payments_volume:/var/lib/postgresql/data
    networks:
      - orderly-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d orderly-payments" ]
      interval: 5s
      timeout: 5s
      retries: 10

  payment-service-liquibase:
    image: liquibase/liquibase:4.25
    restart: "no"
    depends_on:
      payment-service-db:
        condition: service_healthy
    volumes:
      - ./payment-service/src/main/resources/db/changelog:/liquibase/changelog
    command: update
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://payment-service-db:5432/orderly-payments
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: postgres
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/db.changelog-master.yaml
    networks:
      - orderly-net

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8086:8086"
    depends_on:
      payment-service-liquibase:
        condition: service_completed_successfully
      eureka-server:
        condition: service_healthy
      keycloak:
        condition: service_started
#      redis:
#        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - orderly-net

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - orderly-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8087:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - orderly-net

volumes:
  minio_volume:
  users_volume:
  geo_volume:
  keycloak_data:
  orders-volume:
  restaurants_volume:
  payments_volume:

networks:
  orderly-net:
    driver: bridge
