server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
        routes:
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/users/**
            filters:
              - StripPrefix=1
          - id: geo-service
            uri: lb://GEO-SERVICE
            predicates:
              - Path=/geo/**
          - id: order-service
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/orders/**
          - id: restaurant-service
            uri: lb://RESTAURANT-SERVICE
            predicates:
              - Path=/restaurants/**
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
