spring:
  application:
    name: restaurant-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/orderly-users

  r2dbc:
    url: r2dbc:postgresql://restaurant-service-db:5432/orderly-restaurants
    username: postgres
    password: postgres

  datasource:
    url: jdbc:postgresql://restaurant-service-db:5432/orderly-restaurants
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    hostname: restaurant-service
    prefer-ip-address: false

minio:
  endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: restaurant-menu-items

server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

logging:
  level:
    org.springframework.web: debug
    reactor.netty.http.server: debug
